"""add ingestion_runs table

Revision ID: 5b5092d5ef44
Revises: 
Create Date: 2026-09-29 13:09:40.385918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b5092d5ef44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('success', 'failure', 'no_email', name='ingestionstatus'), nullable=False),
    sa.Column('email_received_at', sa.DateTime(), nullable=True),
    sa.Column('email_subject', sa.String(length=500), nullable=True),
    sa.Column('email_message_id', sa.String(length=200), nullable=True),
    sa.Column('shows_parsed', sa.Integer(), nullable=True),
    sa.Column('shows_upserted', sa.Integer(), nullable=True),
    sa.Column('shows_new', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
